/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IKYCVerification,
  IKYCVerificationInterface,
} from "../../interfaces/IKYCVerification";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "checkKYC",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IKYCVerification__factory {
  static readonly abi = _abi;
  static createInterface(): IKYCVerificationInterface {
    return new Interface(_abi) as IKYCVerificationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IKYCVerification {
    return new Contract(address, _abi, runner) as unknown as IKYCVerification;
  }
}
