/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { KYCVerification } from "./KYCVerification";
export * as factories from "./factories";
export type { IKYCVerification } from "./interfaces/IKYCVerification";
export { IKYCVerification__factory } from "./factories/interfaces/IKYCVerification__factory";
export { KYCVerification__factory } from "./factories/KYCVerification__factory";
